apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rover-bot
  description: roverbot services
  links:
    - title: openshift cluster
      url: https://console-openshift-console.apps.ocp-dev01.lab.eng.tlv2.redhat.com/k8s/ns/rover-bot-gitops/core~v1~Pod
    - title: gitlab
      url: https://gitlab.cee.redhat.com/ilpinto/rover-bot 
    - title: operation slack channel 
      url: https://app.slack.com/client/T027F3GAJ/C04KTDWTEF9
    - title: argocd
      url: https://argocd-argocd.apps.ocp-dev01.lab.eng.tlv2.redhat.com
    - title: quay
      url: https://quay.io/user/ilan_pinto/
  annotations:
      backstage.io/kubernetes-id: rover
      backstage.io/kubernetes-namespace: rover
      quay.io/repository-slug: ilan_pinto/rover_bot
      gitlab.com/project-slug: janus-idp/backstage-showcase
      argocd/app-name: rover
spec:
  type: website
  lifecycle: production
  owner: cloud-native-team
  system: bots
